### PR TITLE
Pls just make the mod balanced for vampires just as it is for hunters

### PR DESCRIPTION
**Pull request by itzhak-glitch**
The mod is just unbalanced for vampires (examples: attack speed, attack damage, general strength and hunters 20 advantages on them) and I hate it staying like that and even getting more unbalanced, especially in recent updates so please make vampires powerful just as much or even stronger because the mod is more based on vampires then hunters.

### CODE REVIEW

**Comment by lunofe** [comment]
Not sure what you tried to do here, I'll just assume you're new to GitHub and had no idea what a pull request does.

**Comment by itzhak-glitch** [comment]
What do you think every other person pull requests for? suggestions for the mod and bug fixes, aren't they? im trying to do the same

**Comment by itzhak-glitch** [comment]
And when you look at the mod you can see as much, it is unbalanced

**Comment by lunofe** [comment]
Pull requests are for merging code changes. You're looking for [this](https://github.com/TeamLapen/Vampirism/issues/new/choose).

**Comment by itzhak-glitch** [comment]
thx

**Pull request closed without merging**
