### PR TITLE
Biome Weight from config is ignored.

### PR DESCRIPTION
**Pull request by erebus42**
Changed it to use the value from BalanceGeneral.VAMPIRE_FOREST_WEIGHT

This is my minecraft related PR, but this seemed like an easy fix.

### CODE REVIEW

**Comment by maxanier** [comment]
Any reason you closed this? Looks like a valid bug and a working fix.

**Comment by erebus42** [comment]
I wasn't sure, and the failed test kinda scared me off. I can re-open it if
you'd like.

**Comment by erebus42** [comment]
Re-opened.  Also was this the correct branch? It looks like the build failure was unrelated to my change.

**Comment by erebus42** [comment]
I actually left the name change out, since it was referenced elsewhere. the comment is incorrect.  This is just the use config weight change.

**Comment by maxanier** [comment]
The branch is correct.
However, the failed build is related to this change.
The balance config system creates the balance class objects only at startup and loads the values from the config files during preinit. Therefore all config values are non final and non static (I know the all caps are misleading), so you cannot access the biome weight by `BalanceGeneral.VAMPIRE_FOREST_WEIGHT` but you need to do `Balance.general.VAMPIRE_FOREST_WEIGHT` (all initiated balance objects are stored in the Balance class in static variables).
Additionally, the value might not be available when the BiomeGenVampireForest class is loaded so it should not be assigned to a final static variable (even though it is likely that the class is only loaded after preinit).

I would suggest completely removing the GEN_WEIGHT field and just using `Balance.general.VAMPIRE_FOREST_WEIGHT` in the ModBiomes initialisation.

[I will do this if you want]

**Comment by maxanier** [comment]
Thanks for reporting and fixing

**Pull request merged**
