### PR TITLE
closes #480 Alchemical Cauldron inventory side configuration

### LINKED ISSUE #480: [Bug] Alchemical Cauldron And Hopper
## Versions
- Minecraft: 1.12.2
- Forge: 14.23.5.2816
- Vampirism: 1.5.1

## Issue Description
Placing a hopper under an Alchemical Cauldron will consume the coal (or any fuel) from the Alchemical Cauldron instead of the Alchemical Cauldron's product (such as Pure Salt)

This hinders the ability to create an "automated brewing" style production (such as with vanilla Brewing Stands, see image 1)

## Reproduce Steps
Go into a single player world with creative mode (a flat world will do)
Unlock the Hunter Skill "Basic Alchemy"
Place a hopper pointing into a chest
Place an Alchemical Cauldron on top of the hopper
Insert one piece of coal into the Alchemical Cauldron
Insert one water bucket into the Alchemical Cauldron

Pure Salt will not be produced due to the coal escaping the Alchemical Cauldron

## Additional Information
In late game of Minecraft, after gathering many resources (see image 2) automating production is very useful.
My hope is that Hunters will be able to automate production using the Alchemical Cauldron in the late game phase.

--
Image 1 - Automated brewing from brewing stands in survival. 

Image 2 - Some resources I gathered in survival. Automation will be useful.

### PR DESCRIPTION
**Pull request by Cheaterpaul**
closes #480 Alchemical Cauldron inventory side configuration

### CODE REVIEW

**Comment by maxanier** [comment]
Is there still a way to insert fuel and liquid items?
Seems like these slots are not accessible anymore

**Comment by Cheaterpaul** [comment]
state now:
north/east/west/top-> insert ingredient,liquid,fuel
south/bottom -> extract result

should all inventory slots be accessible from everywhere, but extracting only for the result?
new:
north/east/west/top/south/bottom-> insert ingredient,liquid,fuel
north/east/west/top/south/bottom -> extract result (or only south/bottom)

edit i see your point @maxanier

**Comment by PendragonII** [comment]
Cheatpaul, the design you created for allowing automation of alchemical cauldrons appears to fit and looks okay to go.
Edit 2: State New

**Comment by Cheaterpaul** [comment]
the "state now" or the "new" one?

**Comment by lunofe** [comment]
~~State "new"~~
**EDIT:** Nevermind, "state now".

**Comment by maxanier** [comment]
I would say it should work similar to the furnance or brewing stand.
However, it the "extra" item slot accepts any item (including fuel items) so fuel and extra item have to be inserted from a different side.
E.g.: From the bottom you pull out the result, from the side you fill in fuel and from the top the water and the extra item (making sure the holy water is only ever placed in the dedicated slot)

**Comment by PendragonII** [comment]
> E.g.: From the bottom you pull out the result, from the side you fill in fuel and from the top the water and the extra item (making sure the holy water is only ever placed in the dedicated slot)

Fantastic! This will allow for great flexibility in the type of automation.

**Pull request merged**
